# for forestry, see https://forestry.io/docs/faqs/how-to-use-yaml-json-front-matter-w-hugo/
metaDataFormat: "yaml"

module:
  mounts:
    # default mounts
    - source: layouts
      target: layouts
    - source: static
      target: static
    - source: data
      target: data
    - source: content
      target: content
    - source: i18n
      target: i18n
    - source: assets
      target: assets
    # all assets relating to layouts are in the layouts dir
    # this allows html/css/js to live side-by-side
    - source: layouts
      target: assets
    # add js chunks to static
    - source: assets/js
      target: static/js