module:
  mounts:
    # default mounts
    - source: layouts
      target: layouts
    - source: static
      target: static
    - source: data
      target: data
    - source: content
      target: content
    - source: i18n
      target: i18n
    # images headless
    - source: ../../images
      target: content/images
    # css files used here
    - source: layouts-client/src
      target: assets
    - source: assets
      target: assets
    - source: assets
      target: static
    # js entry points
    - source: layouts-client/dist
      target: assets
    # js chunks
    - source: layouts-client/dist
      target: static
    # layout modules
    - source: modules/html
      target: layouts/partials/modules
    - source: modules/css
      target: assets/modules
    # deprecated layout modules
    - source: modules-deprecated/html
      target: layouts/partials/modules
    - source: modules-deprecated/css
      target: assets/modules