# for forestry, see https://forestry.io/docs/faqs/how-to-use-yaml-json-front-matter-w-hugo/
metaDataFormat: "yaml"

module:
  mounts:
    # default mounts
    - source: layouts
      target: layouts
    - source: static
      target: static
    - source: data
      target: data
    - source: content
      target: content
    - source: i18n
      target: i18n
    - source: assets
      target: assets
    # all assets relating to layouts are in the layouts dir
    # this allows html/css/js to live side-by-side
    - source: layouts
      target: assets
    # this is a dummy import to get the `importers` dir
    # into the hugo vendor dir for sites
    # enables sites to vendor this dir and run the importers
    # from there (instead of trying to figure out the cache location)
    - source: importers
      target: assets/dummy-import-do-not-use