---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: demo/content
  label: Pages
  create: all
  match: "**/*"
  templates:
  - page
  - collection
  - deprecated-page
- type: directory
  path: demo/products/collections
  label: Collections
  create: none
  match: "*/*"
  templates:
  - collection
- type: document
  path: demo/i18n/en.json
  label: Strings
- type: document
  path: demo/data/menus.json
  label: Menus
- type: document
  path: demo/data/announcements.json
  label: Announcements
- type: document
  path: demo/data/pixels.yaml
  label: Pixels
- type: document
  path: i18n/en.json
  label: Translations
  match: "**/*"
upload_dir: demo/images
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.74.3
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv/demo"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.71.1
