---
label: Product List
hide_body: true
display_field: title
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: collection
  type: text
  config:
    required: true
  label: Collection
- name: split_colors
  type: boolean
  label: Split products into colors
  description: If set, will split products into separate items according to colors.
- name: limit
  type: number
  description: Limit number of products to show. Leave blank or use zero to show all
    products in collection.
  default: 10
  required: true
  config:
    min: 
    max: 
    step: 
  label: Number of products to show
- name: show_all
  type: text
  config:
    required: false
  label: Show all button text
  description: If there are more products to show than the limit, a "Show All" button
    will be shown. By default, the button text will be "Sold Out" or whatever is defined
    in the translation file, but you can override that default here if you wish.
- name: collectionref
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: collections
      file: 
      path: 
  label: Collection Reference
  hidden: true
- name: align
  type: select
  default: []
  config:
    required: false
    options:
      - left
      - right
    source:
      type: simple
      section:
      file:
      path:
  label: Items alignment
  description: By default and if this is blank, items are centered.
- name: columnstablet
  type: select
  default: []
  config:
    required: false
    options:
      - '2'
      - '3'
    source:
      type: simple
      section:
      file:
      path:
  label: Columns on tablet
  description: Number of columns to output on tablet sized screens. Leave blank for
    default auto-fill behavior.
- name: columnsdesktop
  type: select
  default: []
  config:
    required: false
    options:
      - '3'
      - '4'
    source:
      type: simple
      section:
      file:
      path:
  label: Columns on desktop
  description: Number of columns to output on desktop sized screens. If left blank,
    it inherits the settings from tablet.
- name: carousel_enabled
  type: boolean
  label: Carousel Enabled
  description: Enables carousel functionality
- name: carousel_dots
  type: boolean
  label: Carousel Dots
  description: Show dot indicators
  showOnly:
    field: carousel_enabled
    value: true
  default: true
- name: carousel_arrows
  type: boolean
  label: Carousel Arrows
  description: Show Prev/Next Arrows
  showOnly:
    field: carousel_enabled
    value: true
- name: carousel_autoplay
  type: boolean
  label: Carousel Autoplay
  showOnly:
    field: carousel_enabled
    value: true
  description: Enables Autoplay
- name: carousel_autoplay_speed
  type: number
  label: Carousel Autoplay Speed
  description: Autoplay Speed in milliseconds
  default: 7000
  required: true
  config:
    min:
    max:
    step:
  showOnly:
    field: carousel_autoplay
    value: true

