---
label: Product Page Settings
hide_body: true
fields:
- type: field_group_list
  name: links
  label: Links below description
  fields:
  - type: text
    name: title
    label: Link title
  - name: type
    type: select
    default: link
    config:
      required: true
      options:
      - link
      - modal
      source:
        type: simple
        section: 
        file: 
        path: 
    label: Link type
    description: Select `link` if you want a regular link to an existing page. The
      link opens up in a new tab.<br>Select `modal` if you want to specify content
      for a pop-up modal instead.
  - type: text
    name: link
    label: Link URL
    config:
      required: false
    showOnly:
      field: type
      value: link
  - name: content
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: markdown
    label: Content
    description: Modal contents. Use markdown if needed.
    showOnly:
      field: type
      value: modal
  description: Links to show between the product description and the features etc.
    section
- type: field_group
  name: accordion
  label: Features etc. section headings
  fields:
  - type: text
    name: info
    label: Features
    description: This is the section of the product description currently under "[product][info]"
    config:
      required: true
  - type: text
    name: mats
    label: Materials
    description: This is the section of the product description currently under "[product][mats]"
    config:
      required: true
  - type: text
    name: care
    label: Care
    description: This is the section of the product description currently under "[product][care]"
    config:
      required: true
  description: Headings for the "accordion" that shows features, materials and care
    instructions.
- type: field_group_list
  name: size_guide
  label: Size guide
  fields:
    - type: text
      name: tag
      label: Tag name
      description: Tag name to match. For example "SizeClothing".
      config:
        required: true
    - type: text
      name: title
      label: Title
      description: What to show as the title / cta. For instance "Size guide".
      config:
        required: true
    - type: textarea
      name: modal
      label: Pop-up contents
      description: Contents for the pop-up that shows when you click title / cta.
        You can use markdown here.
      config:
        required: true
        wysiwyg: true
        schema:
          format: markdown
  description: Configuration for product tags that should output size guide.
- type: field_group_list
  name: features
  label: Product features
  fields:
  - type: text
    name: tag
    label: Tag name
    description: Tag name to match. This is the "Waterproof" part of the example tag
      "Waterproof:3000".
    config:
      required: true
  - type: text
    name: title
    label: Title
    description: What to show as the title for this feature. For instance "Waterproof
      levels".
    config:
      required: true
  - type: text
    name: description
    label: Description
    config:
      required: true
    description: What the specific description of the product feature should be based
      on the tag. Please insert "VALUE" where the tag value should be placed. For
      instance, the description "Waterproof at least VALUE mm" and product tag "Waterproof:3000"
      would render "Waterproof at least 3000 mm" as the specific description for that
      product tag.
  - type: textarea
    name: modal
    label: Pop-up contents
    description: Contents for the pop-up that shows when you click for more info.
      You can use markdown here. This field is optional, leave blank to disable the
      pop-up.
    config:
      wysiwyg: true
      schema:
        format: markdown
  - type: field_group_list
    name: values
    label: Icons
    fields:
    - type: text
      name: value
      label: Tag value
      description: Which tag value this icon corresponds to. This is needed in order
        to highlight the correct icon based on the product tag value. For instance,
        if you enter "3000" here, the product tag "Waterproof:3000" will cause this
        icon to be highlighted.
      config:
        required: true
    - type: file
      name: icon
      label: Icon
      description: Icon <strong>as an SVG file</strong>. It is very important that
        the icon is in SVG format as otherwise the highlighting will not work.
    description: Icons to show for this particular tag
  description: Configuration for product tags that should output additional icons
    and descriptions
- type: boolean
  name: reviews
  label: Enable reviews
  description: Enable reviews on the product page. If there are no reviews to show
    and yotpo has not been connected to this site, there's no need to enable the reviews
    element.
- name: reviews_hide_name
  type: boolean
  label: 'Reviews: Hide Name'
  description: Hide the reviewer name in the product page reviews section.
  showOnly:
    field: reviews
    value: true
- type: boolean
  name: klarnabanner
  label: Enable Klarna payment plan banner
  description: Show Klarna "4 interest-free payments ..." banner. The banner is in
    English, and will show prices as dollars and with two decimals! E.g. "$12.95".
- name: paymentlogos
  type: field_group_list
  fields:
  - name: name
    type: text
    config:
      required: false
    label: Name
    description: Name of the payment provider
  - name: type
    type: select
    default: []
    config:
      required: false
      options:
      - External SVG
      source:
        type: simple
        section: 
        file: 
        path: 
    label: Type
  - name: src
    type: text
    config:
      required: false
    label: Image URL
    description: Full URL to the image (what you might see in the browser bar).
    showOnly:
      field: type
      value: External SVG
  config:
    min: 
    max: 
    labelField: name
  label: Payment Provider Logos
  description: These will show up under the "Add to Cart" button.
pages:
- demo/data/productpage.yaml
