---
label: Product List
hide_body: true
display_field: title
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: collection
  type: text
  config:
    required: true
  label: Collection
- name: limit
  type: number
  description: Limit number of products to show. Leave blank or use zero to show all
    products in collection.
  default: 10
  required: true
  config:
    min: 
    max: 
    step: 
  label: Number of products to show
- name: show_all
  type: text
  config:
    required: false
  label: Show all button text
  description: If there are more products to show than the limit, a "Show All" button
    will be shown. By default, the button text will be "Sold Out" or whatever is defined
    in the translation file, but you can override that default here if you wish.
- name: collectionref
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: collections
      file: 
      path: 
  label: Collection Reference
  hidden: true
