name: Dispatch Release Events
on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - .github/workflows/release-dispatch.yml
jobs:
  dispatch:
    strategy:
      matrix:
        repo: 
          - reima-ecom/north-america
          - reima-ecom/japan
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GHA_DISPATCH_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: theme-release