name: Release on push to master
on:
  push:
    branches:
      - master
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - name: Create release
        run: npx semantic-release