name: Dispatch Release Events
on:
  release: published
jobs:
  dispatch:
    strategy:
      matrix:
        repo: 
          - north-america
          - japan
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GHA_DISPATCH_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: theme-release